version: "3.8"

services:
  api:
    build: .
    container_name: subscription_api
    ports:
      - "${PORT:-3000}:3000"
    env_file: .env.development.local
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: subscription_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
